// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuthSession struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AuthUser struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Disabled     bool
	CreatedAt    time.Time
}
