// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth.sessions (token_hash, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO auth.users (id, email, name, password_hash, disabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Disabled     bool
	CreatedAt    time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Disabled,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth.sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth.sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM auth.sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, disabled, created_at
FROM auth.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT u.id, u.email, u.name, u.password_hash, u.disabled, u.created_at
FROM auth.sessions s
JOIN auth.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > $2 AND NOT u.disabled
`

type GetUserBySessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) GetUserBySession(ctx context.Context, arg GetUserBySessionParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserBySession, arg.TokenHash, arg.ExpiresAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, disabled, created_at
FROM auth.users
ORDER BY name, id
`

type ListUsersRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Disabled  bool
	CreatedAt time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
UPDATE auth.users
SET disabled = $2
WHERE id = $1
`

type SetUserDisabledParams struct {
	ID       uuid.UUID
	Disabled bool
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.Disabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
